#!/bin/zsh

export PATH=$HOME/bin:$PATH

export XDG_DATA_HOME=$HOME/.local/share/
export XDG_CONFIG_HOME=$HOME/.config/
export XDG_CACHE_HOME=$HOME/.cache/

which chromium &>/dev/null && export BROWSER=/usr/bin/chromium
export WINEPREFIX=$HOME/.local/share/wineprefixes/win32
export HISTFILE=$XDG_DATA_HOME/zsh/zsh_history
export SAVEHIST=1000
export HISTSIZE=1000
export GTK_IM_MODULE=xim
export PYTHONSTARTUP=~/.config/python/startup
export MODELSIM_TCL=~/.config/questasim.tcl


if [[ $HOST == maelstrom ]]; then
    export PATH=$PATH:$HOME/.gem/ruby/1.9.1/bin:/opt/gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux/bin
    export GOPATH=~/devel/go
    export LOGOLIB=/usr/lib/logo/logolib
    export LM_LICENSE_FILE=/opt/altera/13.1/license.dat
fi
